### PR TITLE
Use miral for screen events

### LINKED ISSUE #1094: External display does not work initially
- Device: Nexus 5
- Channel: Edge
- Build: 16.04 (2019-04-10/2)

### Steps to reproduce
1. Connect the device to an external display i.e. Nexus 5 via slimport adapter

### Expected behavior
The device screen should become a virtual touchpad + OSK
The external display should display the Unity 8 shell.

### Actual behavior
The device screen stays the same and shows the Unity 8 shell and does NOT react to any touch.
The external display is blank.

### Additional Information
Restarting Unity 8 will make the external display work.

### PR DESCRIPTION
**Pull request by mariogrip**
This moves to using mirals screen events to add/remove/update screens.
Before this was done by listening to compositor restart events and
updating screens based on display configs diffs from mir

This needs: https://github.com/ubports/mir-android-platform/pull/19 and https://github.com/ubports/mir/pull/21
This fixes: https://github.com/ubports/ubuntu-touch/issues/1094

### CODE REVIEW

**Comment by gerboland** [comment]
LGTM. You've kept the unusual looking move-window-between-screens logic I wrote. That was necessary as if you didn't, a window was considered hidden and wouldn't render. I've no idea if newer Qt has changed that behaviour.

Only thing I'd be cautious about is the code run on Mir's thread (just 1 thread? Multiple threads?) and making sure races aren't introduced.

**Comment by mariogrip** [comment]
> LGTM. You've kept the unusual looking move-window-between-screens logic I wrote. That was necessary as if you didn't, a window was considered hidden and wouldn't render. I've no idea if newer Qt has changed that behaviour.
> 
> Only thing I'd be cautious about is the code run on Mir's thread (just 1 thread? Multiple threads?) and making sure races aren't introduced.

I might remove that logic as it's never executed as canUpdateExistingScreen always return true anyway (there is a TODO there, not sure why)

After checking, you are correct about potential races as mir's events are async, so i added a mutexLocker to avoid any races :)

**Comment by mariogrip** [comment]
Ok, should be good for test and review now :)

**Comment by mariogrip** [comment]
I fixed a race condition with unity8, that seems to have fixed the random crashes and *stuck in secondscreen*. This seems to work really well for me on both nexus 5 and M10. 

**Please note** it seems to crash still from greeter (due to osk) and with osk open, this is a different issue not related to this.

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
I'm unsure which PR in the secondscreen set should actually get this review, so I'm picking this one.

It appears that this fixes adding and removing an external wired display on the Nexus 5. However, I'm still having issues with the following configurations:

* Removing a wired display on the Nexus 7 results in the screen not going back to normal, staying on the touchpad ([unity8.log here](https://paste.ubuntu.com/p/qwHhcVpV6h/))
* Removing a wireless display on the Fairphone 2 results in the screen not going back to normal, staying on the touchpad ([unity8.log here](https://paste.ubuntu.com/p/2WZysFN7pq/))

It appears that the compositor is indeed restarting as expected, but Unity8 is still not changing as it should.

Edit: The change *does* work as expected when removing a wireless external display from the OnePlus One. Log here: https://paste.ubuntu.com/p/g2sHYMrR8r/

**Comment by UniversalSuperBox** [comment]
Scratch my report for the Fairphone 2. I had installed the secondscreen patch incorrectly.

On the Nexus 7, after a full reinstall, I can get the second screen to detach properly *most of the time*. However, Scale will never go back to the tablet's size until it is rebooted.

**Comment by UniversalSuperBox** [comment]
I believe the failure of pr-merge is due to Jenkins trying to merge on the wrong commit. Ignore it.

**Review by UniversalSuperBox — CHANGES_REQUESTED** [review]
With https://github.com/ubports/mir-android-platform/pull/19 merged, it's a little easier to see exactly what's different when this PR is installed or not.

I think I've determined that this races all over the place. :)

Without this PR installed, adding a screen at runtime results in Lomiri recognizing the change but not acting on it. If it is restarted with `$ restart unity8`, it will restart with both screens in use. If a screen is removed, the remaining screen switches to being the primary.

Well, most of the time. Sometimes Unity crashes. I need to get more debugging.

With this installed, it's a toss-up what's going to happen when you plug in or unplug a screen. Sometimes
a full plug-unplug cycle works correctly: primary display changes, touchpad appears, then touchpad disappears to go back to single-screen mode. Sometimes the unplug event doesn't execute correctly and we end up stuck at the touchpad. Most of the time, some combination of Lomiri and the compositor crash.

When Lomiri crashes, the last line in the log is usually:

```
[2020-03-24:14:24:58.962] qtmir.screens: QtCompositor::stop
```

or 

```
[2020-03-24:14:24:58.963] qtmir.screens: ScreensModel::onCompositorStopping
```

Additionally, the system-compositor may show multiple output change messages (the ones that list all the outputs). Only one of these messages will invalidate the buffers. I suspect this is due to changing the orientation of the external screen before compositing has begun again, but I can't guarantee it.

Overall, more investigation needed. Definitely not ready for merge.

**Comment by UniversalSuperBox** [comment]
Qtmir has moved to https://gitlab.com/ubports/core/qtmir

**Pull request closed without merging**
