### PR TITLE
Adjust for gmock 1.10.0

### PR DESCRIPTION
**Pull request by z3ntu**
Might need some `#if`

### CODE REVIEW

**Comment by mariogrip** [comment]
Seems like it needs some #if :(

**Comment by z3ntu** [comment]
Ugh gtest of course doesn't export the version in any easy way at all... I guess copying parts of https://github.com/MirServer/mir/blob/master/tests/CMakeLists.txt#L45-L63 should expose it for us...  (yay for regex)

**Comment by z3ntu** [comment]
I think I got it!

Alpine Linux:
```
-- Checking for module 'gtest'
--   Found gtest, version 1.10.0
Using GTest v1.10.0
```
Ubuntu xenial:
```
-- Checking for module 'gtest'
--   No package 'gtest' found
CMake Warning at tests/CMakeLists.txt:5 (message):
  'gtest' not found with pkg-config, assuming v1.7.0


Using GTest v1.7.0
```

Btw I was struggling with this for a couple of hours today because CMake was so nice to not give me a version number using `find_package(GTest)` even though `/usr/lib/cmake/GTest` is defining it but as cmake is bundling it's own version of this module `/usr/share/cmake-3.17/Modules/FindGTest.cmake` which is **not** defining a version number it was very very annoying...

**Comment by z3ntu** [comment]
The macro & .h file is (mostly) copied from mir btw. Licensing-wise I think this should be fine

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Pull request merged**
